# defining the name of the workflow
name: CI/CD Pipeline

# specifying this workflow will get triggered if we push anything to the main branch
on:
  push:
    branches:
      - main

# adding environment variables
env:
  AWS_REGION: us-east-1
  

# defining the jobs
jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Debugging step to check the secrets
      - name: Print secrets for debugging
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "REGION_NAME: ${{ secrets.REGION_NAME }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b8c74de753fbcb4868bf2011fb2e15826ce973af
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Echo AWS Region
        run: echo "AWS Region is ${{ secrets.REGION_NAME }}"
