# defining the name of the workflow
name: CI/CD Pipeline

# specifying this workflow will get triggered if we push anything to the main branch
on:
  push:
    branches:
      - main

# defining the jobs
jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION_NAME }}

      - name: Echo AWS Region
        run: echo "AWS Region is ${{ secrets.REGION_NAME }}"
