# defining the name of the workflow (Containerizing the Image and deploying it to ECS) ==> Continuous Delivery
name: CI/CD Pipeline

# specifying this workflow will get triggered if we push anything to the main branch.
on:
  push:
    branches:
       - main

# adding environment variables
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: news_article_search_engine
  CONTAINER_NAME: news_article_search_engine


# defining the jobs
jobs:
  # defining Continous integration which tested our application when any push happens
  Continous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      
      - name: Run tests with pytest
        run: pytest test.py